"""
Content validation and verification system.

This module provides validation capabilities for agent decisions, actions,
and responses. Currently implemented as a stub, it's designed to be extended
with LLM-based validation for intelligent content verification and safety
checks.

Key Features:
- Content validation interface
- Memory integration for context
- Extensible architecture for LLM validation
- Safety and quality checks
- Future: LLM-based intelligent validation

Future Enhancements:
- Integration with Language Models for content validation
- Safety filtering and content moderation
- Response quality assessment
- Fact-checking capabilities
- Bias detection and mitigation
"""

import logging
from typing import Any, Dict, List, Optional, Callable

from memory.memory import Memory


class Validator:
    """
    Content validation component for agent responses and actions.
    
    This class provides validation capabilities for various types of content
    generated by the agent. It's designed to work with memory systems to
    maintain context about validation history and patterns.
    
    Attributes:
        memory: Memory system for storing validation context and history
        validation_rules: Dictionary of validation rules and criteria
        validation_history: List of recent validation results
    """
    
    def __init__(self, memory: Memory) -> None:
        """
        Initialize the validator with memory integration.
        
        Args:
            memory: Memory system for storing validation context
        """
        self.memory = memory
        self.validation_rules: Dict[str, Any] = {}
        self.validation_history: List[Dict[str, Any]] = []
        
        logging.info("Content validator initialized")
    
    def validate(self, content: Any) -> bool:
        """
        Validate content for safety, quality, and appropriateness.
        
        This method performs validation checks on agent-generated content.
        Currently returns True for all content, but is designed to be
        extended with LLM-based validation for intelligent verification.
        
        Args:
            content: The content to validate (can be any type)
            
        Returns:
            bool: True if content passes validation, False otherwise
            
        Note:
            This is currently a stub implementation. Future versions will
            use Language Models for intelligent content validation.
        """
        try:
            logging.debug(f"Validating content: '{str(content)[:100]}...'")
            
            # TODO: Implement LLM-based validation
            # This would involve:
            # 1. Content analysis using language models
            # 2. Safety and quality checks
            # 3. Fact verification
            # 4. Bias detection
            
            # For now, perform basic validation
            validation_result = self._basic_validation(content)
            
            # Store validation result
            validation_record = {
                "content": str(content)[:200],  # Truncate for storage
                "result": validation_result,
                "method": "basic"
            }
            self.validation_history.append(validation_record)
            
            # Keep only recent history (last 100 entries)
            if len(self.validation_history) > 100:
                self.validation_history = self.validation_history[-100:]
            
            # Store in memory
            self.memory.add("validation_result", validation_record)
            
            logging.debug(f"Validation result: {validation_result}")
            return validation_result
            
        except Exception as e:
            logging.error(f"Error during validation: {e}")
            return False
    
    def _basic_validation(self, content: Any) -> bool:
        """
        Perform basic validation checks on content.
        
        This method implements simple validation rules that don't require
        LLM processing. It checks for basic issues like empty content,
        excessive length, or obvious problems.
        
        Args:
            content: The content to validate
            
        Returns:
            bool: True if content passes basic validation
        """
        try:
            # Convert content to string for analysis
            content_str = str(content)
            
            # Check for empty or null content
            if not content_str or content_str.strip() == "":
                logging.debug("Validation failed: Empty content")
                return False
            
            # Check for excessive length (prevent memory issues)
            if len(content_str) > 10000:
                logging.debug("Validation failed: Content too long")
                return False
            
            # Check for obvious error indicators
            error_indicators = ["error:", "failed:", "exception:", "traceback:"]
            if any(indicator in content_str.lower() for indicator in error_indicators):
                logging.debug("Validation failed: Contains error indicators")
                return False
            
            # Basic validation passed
            return True
            
        except Exception as e:
            logging.error(f"Error in basic validation: {e}")
            return False
    
    def validate_response(self, response: str, context: str = "") -> bool:
        """
        Validate a response using LLM-based analysis.
        
        Args:
            response: The response to validate
            context: Optional context for validation
            
        Returns:
            bool: True if response is valid, False otherwise
        """
        try:
            # TODO: Implement LLM-based validation
            # This would use the LLM to analyze the response for:
            # - Relevance to the context
            # - Factual accuracy
            # - Appropriate tone and style
            # - Completeness of information
            
            # For now, use enhanced keyword-based validation
            return self._validate_with_keywords(response, context)
            
        except Exception as e:
            logging.error(f"Error in LLM-based validation: {e}")
            # Fall back to basic validation
            return self.validate(response)
    
    def _validate_with_keywords(self, response: str, context: str = "") -> bool:
        """
        Enhanced keyword-based validation with context awareness.
        
        Args:
            response: The response to validate
            context: Context for validation
            
        Returns:
            bool: True if response passes validation
        """
        try:
            # Basic checks
            if not response or len(response.strip()) < 5:
                return False
            
            # Check for error indicators
            error_indicators = ["error:", "failed:", "exception:", "traceback:", "❌", "⚠️"]
            if any(indicator in response.lower() for indicator in error_indicators):
                return False
            
            # Check for context relevance (if context provided)
            if context:
                context_words = set(context.lower().split())
                response_words = set(response.lower().split())
                common_words = context_words.intersection(response_words)
                
                # If no common words, response might not be relevant
                if len(common_words) < 2:
                    return False
            
            # Check for appropriate length
            if len(response) > 5000:  # Too long
                return False
            
            # Check for appropriate content
            if response.count(" ") < 3:  # Too short
                return False
            
            return True
            
        except Exception as e:
            logging.error(f"Error in keyword validation: {e}")
            return False
    
    def validate_action(self, action: str, parameters: Optional[Dict[str, Any]] = None) -> bool:
        """
        Validate an action with action-specific rules.
        
        Args:
            action: The action to validate
            parameters: Optional parameters for the action
            
        Returns:
            bool: True if action is valid, False otherwise
        """
        try:
            # TODO: Implement action-specific validation
            # This would validate different types of actions:
            # - Web search: Check query length, content appropriateness
            # - Browse web: Validate URLs, check for malicious content
            # - Memory operations: Check content length, relevance
            # - Tool usage: Validate tool parameters
            
            # For now, use enhanced action validation
            return self._validate_action_enhanced(action, parameters)
            
        except Exception as e:
            logging.error(f"Error in action validation: {e}")
            return False
    
    def _validate_action_enhanced(self, action: str, parameters: Optional[Dict[str, Any]] = None) -> bool:
        """
        Enhanced action validation with action-specific rules.
        
        Args:
            action: The action to validate
            parameters: Optional parameters for the action
            
        Returns:
            bool: True if action passes validation
        """
        try:
            # Basic action validation
            if not action or len(action.strip()) < 3:
                return False
            
            action_lower = action.lower()
            
            # Web search validation
            if "search" in action_lower or "web" in action_lower:
                return self._validate_web_action(parameters)
            
            # Browse validation
            if "browse" in action_lower or "navigate" in action_lower:
                return self._validate_browse_action(parameters)
            
            # Memory validation
            if "memory" in action_lower or "save" in action_lower:
                return self._validate_memory_action(parameters)
            
            # Tool validation
            if "tool" in action_lower:
                return self._validate_tool_action(parameters)
            
            # Default validation
            return True
            
        except Exception as e:
            logging.error(f"Error in enhanced action validation: {e}")
            return False
    
    def _validate_web_action(self, parameters: Optional[Dict[str, Any]]) -> bool:
        """Validate web search actions."""
        if not parameters:
            return False
        
        query = parameters.get("query", "")
        if not query or len(query.strip()) < 2:
            return False
        
        # Check for inappropriate content
        inappropriate_words = ["hack", "crack", "illegal", "malware"]
        if any(word in query.lower() for word in inappropriate_words):
            return False
        
        return True
    
    def _validate_browse_action(self, parameters: Optional[Dict[str, Any]]) -> bool:
        """Validate browse actions."""
        if not parameters:
            return False
        
        url = parameters.get("url", "")
        if not url:
            return False
        
        # Basic URL validation
        if not url.startswith(("http://", "https://")):
            return False
        
        # Check for suspicious domains
        suspicious_domains = ["malware", "phishing", "scam"]
        if any(domain in url.lower() for domain in suspicious_domains):
            return False
        
        return True
    
    def _validate_memory_action(self, parameters: Optional[Dict[str, Any]]) -> bool:
        """Validate memory operations."""
        if not parameters:
            return False
        
        content = parameters.get("content", "")
        if not content:
            return False
        
        # Check content length
        if len(content) > 10000:  # Too long
            return False
        
        if len(content) < 5:  # Too short
            return False
        
        return True
    
    def _validate_tool_action(self, parameters: Optional[Dict[str, Any]]) -> bool:
        """Validate tool usage."""
        if not parameters:
            return False
        
        tool_name = parameters.get("tool_name", "")
        if not tool_name:
            return False
        
        # Check if tool name is valid
        valid_tools = ["web_search", "browse_web", "memory_search", "save_memory"]
        if tool_name not in valid_tools:
            return False
        
        return True
    
    def get_validation_stats(self) -> Dict[str, Any]:
        """
        Get statistics about validation history.
        
        Returns:
            dict: Validation statistics and metrics
        """
        try:
            total_validations = len(self.validation_history)
            successful_validations = sum(1 for record in self.validation_history if record.get("result", False))
            
            return {
                "total_validations": total_validations,
                "successful_validations": successful_validations,
                "success_rate": successful_validations / total_validations if total_validations > 0 else 0,
                "recent_validations": len(self.validation_history[-10:]) if self.validation_history else 0,
                "memory_entries": self.memory.count("validation_result")
            }
            
        except Exception as e:
            logging.error(f"Error getting validation stats: {e}")
            return {"error": str(e)}
    
    def clear_history(self) -> None:
        """Clear validation history."""
        self.validation_history.clear()
        logging.info("Validation history cleared")
    
    def add_validation_rule(self, rule_name: str, rule_function: Callable[[Any], bool]) -> None:
        """
        Add a custom validation rule.
        
        Args:
            rule_name: Name of the validation rule
            rule_function: Function that performs the validation
        """
        try:
            self.validation_rules[rule_name] = rule_function
            logging.info(f"Added validation rule: {rule_name}")
        except Exception as e:
            logging.error(f"Error adding validation rule: {e}")
    
    def get_validator_info(self) -> Dict[str, Any]:
        """
        Get information about the validator configuration.
        
        Returns:
            dict: Validator configuration and status information
        """
        return {
            "validation_rules": len(self.validation_rules),
            "validation_history_size": len(self.validation_history),
            "memory_entries": self.memory.count("validation_result"),
            "implementation": "stub (LLM integration planned)"
        }
